import './style.css';

document.querySelector('#app').innerHTML = `
  <header class="site-header"><a class="brand" href="#top" aria-label="Webarrow home"><span class="brand-mark">↗</span><span>web<span class="brand-arrow">arrow</span></span></a><nav class="nav-links" aria-label="Main navigation"><a href="#services">Services</a><a href="#locations">Locations</a><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></nav><button class="theme-toggle" aria-label="Toggle colour theme">◐</button><a class="button button-small button-gradient" href="#audit">Free audit <span>↗</span></a><button class="menu-toggle" aria-label="Open menu">☰</button></header>
  <main id="top">
    <section class="hero section-shell"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> London & North London</p><h1>Helping local businesses get found, get <em>leads</em> and grow.</h1><p class="hero-intro">Websites, SEO, Google Ads and digital solutions for businesses across London and the UK.</p><div class="hero-actions"><a class="button button-gradient" href="#audit">Get a free local SEO audit <span>↗</span></a><a class="button button-outline" href="#work">View our work</a></div></div><div class="hero-photo" role="img" aria-label="London skyline"></div></section>
    <section class="trust-strip"><div class="section-shell trust-grid"><div>◉<strong>Local SEO Experts</strong></div><div>◷<strong>More Calls & Enquiries</strong></div><div>⌁<strong>Results-Driven</strong></div><div>✦<strong>Trusted by UK Businesses</strong></div></div></section>
    <section class="section-shell section" id="locations"><div class="section-heading"><div><p class="eyebrow">01 / We work with</p><h2>Built for businesses<br><em>with somewhere to go.</em></h2></div><p class="heading-copy">From a trusted local service to a growing London brand, we make your next digital move clearer, sharper and more effective.</p></div><div class="industry-grid"><a href="#contact"><span class="industry-image image-restaurant"></span><strong>Restaurants & Cafés</strong><small>Get discovered locally ↗</small></a><a href="#contact"><span class="industry-image image-trades"></span><strong>Trades & Home Services</strong><small>Win more enquiries ↗</small></a><a href="#contact"><span class="industry-image image-health"></span><strong>Healthcare & Clinics</strong><small>Build trust online ↗</small></a><a href="#contact"><span class="industry-image image-professional"></span><strong>Professional Services</strong><small>Look the part ↗</small></a><a href="#contact"><span class="industry-image image-retail"></span><strong>Retail & E-commerce</strong><small>Sell more online ↗</small></a><a href="#contact"><span class="industry-image image-hospitality"></span><strong>Hotels & Hospitality</strong><small>Fill more rooms ↗</small></a></div></section>
    <section class="service-band" id="services"><div class="section-shell"><div class="band-heading"><h2>A complete digital solution<br><em>for every business.</em></h2><a class="text-link" href="#contact">View all services <span>↗</span></a></div><div class="service-grid"><a href="#contact"><span class="service-icon">▣</span><strong>Website Design</strong><small>High-performing, mobile-first</small></a><a href="#contact"><span class="service-icon">⌑</span><strong>E-commerce</strong><small>Sell more online</small></a><a href="#contact"><span class="service-icon">⌖</span><strong>Local SEO</strong><small>Get found in London</small></a><a href="#contact"><span class="service-icon">▥</span><strong>Google Ads</strong><small>Reach the right customers</small></a><a href="#contact"><span class="service-icon">✦</span><strong>AI Solutions</strong><small>Work smarter with AI</small></a><a href="#contact"><span class="service-icon">▤</span><strong>Hosting & Support</strong><small>Safe, secure and reliable</small></a></div></div></section>
    <section class="section-shell section" id="work"><div class="band-heading"><div><p class="eyebrow">02 / Featured work</p><h2>Work that makes<br><em>business sense.</em></h2></div><a class="text-link" href="#contact">View all work <span>↗</span></a></div><div class="work-grid"><article><div class="work-image work-bricks"></div><strong>Bricks & Bobs</strong><small>E-commerce website</small></article><article><div class="work-image work-safe"></div><strong>SafeStart</strong><small>Corporate website</small></article><article><div class="work-image work-law"></div><strong>SBG Solicitors</strong><small>Professional website</small></article></div></section>
    <section class="local-panel" id="about"><div class="section-shell local-layout"><div><p class="eyebrow eyebrow-light">03 / Local, by design</p><h2>Helping businesses<br>across <em>London</em><br>get found.</h2><p>We understand the local search landscape — from North London neighbourhoods to businesses serving customers across the UK.</p><a class="button button-light" href="#contact">See how we can help <span>↗</span></a></div><div class="london-map">✦<span>North London</span><i>⌖</i><b>London</b></div></div></section>
    <section class="audit-section" id="audit"><div class="section-shell audit-layout"><div><p class="eyebrow"><span class="status-dot"></span> Free instant audit · no signup</p><h2>See exactly why your website isn’t bringing <em>customers.</em></h2><p>We check what Google sees on mobile, your technical SEO, speed, security and conversion journey — then give you a clear action plan.</p></div><form class="audit-form"><label for="audit-url">Your website address</label><div><input id="audit-url" type="url" placeholder="yourwebsite.co.uk" required><button class="button button-gradient" type="submit">Run free audit <span>↗</span></button></div><small>No signup. Results in around 30 seconds.</small></form></div></section>
  </main><footer class="site-footer section-shell"><a class="brand" href="#top"><span class="brand-mark">↗</span><span>web<span class="brand-arrow">arrow</span></span></a><span>Web design, visibility & growth for ambitious businesses.</span><span>© ${new Date().getFullYear()} Webarrow</span></footer>`;

document.querySelector('.menu-toggle').addEventListener('click', () => document.querySelector('.nav-links').classList.toggle('is-open'));
